/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tito' at '10/9/16 5:00 PM' with Gradle 2.14.1
 *
 * @author tito, @date 10/9/16 5:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
