/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tito' at '10/14/16 11:04 AM' with Gradle 2.14.1
 *
 * @author tito, @date 10/14/16 11:04 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
